# SwiftShip Delivery Operations — Data Cleaning

This notebook cleans and prepares the raw delivery operations dataset for analysis by handling duplicates, missing values, invalid values, inconsistent dates, and data types.

In [ ]:
import numpy as np 
import pandas as pd

## 1. Load the Raw Dataset

Load the raw delivery operations dataset that was identified and inspected during the data understanding stage.

In [2]:
df = pd.read_csv("../Data/Raw/swiftship_delivery_operations_raw.csv")

In [3]:
df.head()

,order_id,order_date,customer_id,customer_segment,customer_city,warehouse_id,warehouse_city,product_category,quantity,order_value,...,package_weight_kg,promised_delivery_date,dispatch_date,delivery_date,delivery_status,delay_days,weather_condition,return_flag,return_reason,customer_rating
0,ORD100000,2025-02-02,CUST03193,Home Office,Ahmedabad,WH07,Chennai,Grocery,4,1382.68,...,1.37,2025-02-07,2025-02-02,2025-02-08,Delayed,1,Clear,0,NaN,2.3
1,ORD100001,2025-10-10,CUST03881,Home Office,Pune,WH08,Mumbai,Office Supplies,3,1201.50,...,2.74,2025-10-16,2025-10-11,2025-10-17,Delayed,1,Clear,0,NaN,3.1
2,ORD100002,2025-08-27,CUST03568,Corporate,Delhi,WH06,Pune,Office Supplies,4,1070.31,...,7.81,2025-09-01,2025-08-27,2025-09-02,Delayed,1,Clear,0,NaN,3.9
3,ORD100003,2025-06-10,CUST02019,Consumer,Hyderabad,WH12,Delhi,Electronics,4,4117.11,...,5.81,2025-06-12,2025-06-11,2025-06-14,Delayed,2,Rain,0,NaN,4.1
4,ORD100004,2025-06-08,CUST03041,Consumer,Bengaluru,WH04,Bengaluru,Office Supplies,3,1027.56,...,2.17,2025-06-14,2025-06-08,2025-06-16,Delayed,2,Cloudy,1,Late Delivery,3.0

## 2. Remove Duplicate Records

Remove duplicate records and verify that no duplicate rows remain in the dataset.

In [4]:
df.drop_duplicates(inplace = True)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df

,order_id,order_date,customer_id,customer_segment,customer_city,warehouse_id,warehouse_city,product_category,quantity,order_value,...,package_weight_kg,promised_delivery_date,dispatch_date,delivery_date,delivery_status,delay_days,weather_condition,return_flag,return_reason,customer_rating
0,ORD100000,2025-02-02,CUST03193,Home Office,Ahmedabad,WH07,Chennai,Grocery,4,1382.68,...,1.37,2025-02-07,2025-02-02,2025-02-08,Delayed,1,Clear,0,NaN,2.3
1,ORD100001,2025-10-10,CUST03881,Home Office,Pune,WH08,Mumbai,Office Supplies,3,1201.50,...,2.74,2025-10-16,2025-10-11,2025-10-17,Delayed,1,Clear,0,NaN,3.1
2,ORD100002,2025-08-27,CUST03568,Corporate,Delhi,WH06,Pune,Office Supplies,4,1070.31,...,7.81,2025-09-01,2025-08-27,2025-09-02,Delayed,1,Clear,0,NaN,3.9
3,ORD100003,2025-06-10,CUST02019,Consumer,Hyderabad,WH12,Delhi,Electronics,4,4117.11,...,5.81,2025-06-12,2025-06-11,2025-06-14,Delayed,2,Rain,0,NaN,4.1
4,ORD100004,2025-06-08,CUST03041,Consumer,Bengaluru,WH04,Bengaluru,Office Supplies,3,1027.56,...,2.17,2025-06-14,2025-06-08,2025-06-16,Delayed,2,Cloudy,1,Late Delivery,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,ORD124995,2025-05-23,CUST02991,Corporate,Chennai,WH11,Hyderabad,Electronics,4,4167.17,...,9.46,2025-05-28,2025-05-23,2025-06-01,Delayed,4,Rain,0,NaN,2.7
24996,ORD124996,2025-12-23,CUST02830,Consumer,Ahmedabad,WH05,Mumbai,Grocery,1,245.09,...,1.57,2025-12-26,2025-12-24,2025-12-29,Delayed,3,Cloudy,0,NaN,2.8
24997,ORD124997,2025-03-26,CUST02408,Home Office,Bengaluru,WH04,Bengaluru,Furniture,3,3918.27,...,6.13,2025-03-31,2025-03-26,2025-04-04,Cancelled,4,Storm,0,NaN,NaN
24998,ORD124998,2025-07-31,CUST03983,Consumer,Mumbai,WH10,Hyderabad,Furniture,2,2659.21,...,1.35,2025-08-02,2025-08-01,2025-08-02,Delivered,0,Clear,0,NaN,3.2
24999,ORD124999,2025-03-21,CUST00578,Home Office,Pune,WH10,Chennai,Furniture,4,5295.39,...,2.33,2025-03-26,2025-03-21,2025-03-26,Delivered,0,Clear,0,NaN,5.0

## 3. Handle Missing Values

Identify missing values and apply appropriate replacements to categorical and descriptive fields where required.

In [7]:
df.isnull().sum()

order_id                      0
order_date                    0
customer_id                   0
customer_segment            200
customer_city                 0
warehouse_id                  0
warehouse_city                0
product_category              0
quantity                      0
order_value                   0
delivery_partner            125
vehicle_type                  0
shipping_mode                 0
distance_km                   0
package_weight_kg             0
promised_delivery_date        0
dispatch_date                 0
delivery_date                 0
delivery_status               0
delay_days                    0
weather_condition           150
return_flag                   0
return_reason             23496
customer_rating            1187
dtype: int64

In [8]:
df["customer_segment"] = df["customer_segment"].fillna("Unknown")

In [9]:
df.isnull().sum()

order_id                      0
order_date                    0
customer_id                   0
customer_segment              0
customer_city                 0
warehouse_id                  0
warehouse_city                0
product_category              0
quantity                      0
order_value                   0
delivery_partner            125
vehicle_type                  0
shipping_mode                 0
distance_km                   0
package_weight_kg             0
promised_delivery_date        0
dispatch_date                 0
delivery_date                 0
delivery_status               0
delay_days                    0
weather_condition           150
return_flag                   0
return_reason             23496
customer_rating            1187
dtype: int64

In [10]:
df["delivery_partner"] = df["delivery_partner"].fillna("delivery_partner")
df["weather_condition"] = df["weather_condition"].fillna("Unknown")
df["return_reason"] = df["return_reason"].fillna("Not Provided")

In [11]:
df.isnull().sum()

order_id                     0
order_date                   0
customer_id                  0
customer_segment             0
customer_city                0
warehouse_id                 0
warehouse_city               0
product_category             0
quantity                     0
order_value                  0
delivery_partner             0
vehicle_type                 0
shipping_mode                0
distance_km                  0
package_weight_kg            0
promised_delivery_date       0
dispatch_date                0
delivery_date                0
delivery_status              0
delay_days                   0
weather_condition            0
return_flag                  0
return_reason                0
customer_rating           1187
dtype: int64

In [12]:
df.isnull().sum()

order_id                     0
order_date                   0
customer_id                  0
customer_segment             0
customer_city                0
warehouse_id                 0
warehouse_city               0
product_category             0
quantity                     0
order_value                  0
delivery_partner             0
vehicle_type                 0
shipping_mode                0
distance_km                  0
package_weight_kg            0
promised_delivery_date       0
dispatch_date                0
delivery_date                0
delivery_status              0
delay_days                   0
weather_condition            0
return_flag                  0
return_reason                0
customer_rating           1187
dtype: int64

## 4. Handle Invalid Numerical Values

Remove records containing invalid numerical values such as non-positive quantities, order values, distances, package weights, and invalid customer ratings.

In [13]:
df = df[df["quantity"] > 0]

In [14]:
(df["quantity"]<=0).sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 24985 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                24985 non-null  str
 1   order_date              24985 non-null  str
 2   customer_id             24985 non-null  str
 3   customer_segment        24985 non-null  str
 4   customer_city           24985 non-null  str
 5   warehouse_id            24985 non-null  str
 6   warehouse_city          24985 non-null  str
 7   product_category        24985 non-null  str
 8   quantity                24985 non-null  int64
 9   order_value             24985 non-null  float64
 10  delivery_partner        24985 non-null  str
 11  vehicle_type            24985 non-null  str
 12  shipping_mode           24985 non-null  str
 13  distance_km             24985 non-null  float64
 14  package_weight_kg       24985 non-null  float64
 15  promised_delivery_date  24985 non-null  str
 16  dispatch_date           24985 non-null  str
 17  delivery_date           24985 non-null  str
 18  delivery_status         24985 non-null  str
 19  delay_days              24985 non-null  int64
 20  weather_condition       24985 non-null  str
 21  return_flag             24985 non-null  int64
 22  return_reason           24985 non-null  str
 23  customer_rating         23799 non-null  float64
dtypes: float64(4), int64(3), str(17)
memory usage: 4.8 MB

In [16]:
df["customer_rating"] = pd.to_numeric(
    df["customer_rating"],
    errors="coerce"
)

In [17]:
df = df[df["order_value"]>0] 
df = df[df["distance_km"]>0]
df = df[df["package_weight_kg"]>0]
df = df[(df["customer_rating"] > 0) & (df["customer_rating"] <= 5)]

In [18]:
df["delivery_partner"] = df["delivery_partner"].replace("delivery_partner", "Unknown")

## 5. Validate Delivery Dates

Identify and remove records where the delivery timeline is logically inconsistent, such as dispatch occurring before the order or delivery occurring before dispatch.

In [19]:
invalid_rows =  ( (df["dispatch_date"] < df["order_date"]) |
                (df["delivery_date"] < df["dispatch_date"])|
                 (df["delivery_date"] < df["order_date"] ))

invalid_rows.sum()

np.int64(71)

In [20]:
df = df[~invalid_rows]

## 6. Convert Date Columns

Convert order, dispatch, promised delivery, and actual delivery dates into Pandas datetime format for reliable date-based analysis.

In [22]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["delivery_date"] = pd.to_datetime(df["delivery_date"])
df["dispatch_date"] = pd.to_datetime(df["dispatch_date"])
df["promised_delivery_date"] = pd.to_datetime(df["promised_delivery_date"])

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 23698 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                23698 non-null  str
 1   order_date              23698 non-null  datetime64[us]
 2   customer_id             23698 non-null  str
 3   customer_segment        23698 non-null  str
 4   customer_city           23698 non-null  str
 5   warehouse_id            23698 non-null  str
 6   warehouse_city          23698 non-null  str
 7   product_category        23698 non-null  str
 8   quantity                23698 non-null  int64
 9   order_value             23698 non-null  float64
 10  delivery_partner        23698 non-null  str
 11  vehicle_type            23698 non-null  str
 12  shipping_mode           23698 non-null  str
 13  distance_km             23698 non-null  float64
 14  package_weight_kg       23698 non-null  float64
 15  promised_delivery_date  23698 non-null  datetime64[us]
 16  dispatch_date           23698 non-null  datetime64[us]
 17  delivery_date           23698 non-null  datetime64[us]
 18  delivery_status         23698 non-null  str
 19  delay_days              23698 non-null  int64
 20  weather_condition       23698 non-null  str
 21  return_flag             23698 non-null  int64
 22  return_reason           23698 non-null  str
 23  customer_rating         23698 non-null  float64
dtypes: datetime64[us](4), float64(4), int64(3), str(13)
memory usage: 4.5 MB

In [24]:
df.shape

(23698, 24)

In [25]:
df.describe()

,order_date,quantity,order_value,distance_km,package_weight_kg,promised_delivery_date,dispatch_date,delivery_date,delay_days,return_flag,customer_rating
count,23698,23698.000000,23698.000000,23698.000000,23698.000000,23698,23698,23698,23698.000000,23698.000000,23698.000000
mean,2025-07-01 08:45:33.192674,2.985400,2127.705057,22.596308,3.956499,2025-07-05 22:12:01.276057,2025-07-01 20:42:19.961178,2025-07-06 20:07:56.394632,0.913832,0.062495,3.425217
min,2025-01-01 00:00:00,1.000000,210.270000,1.000000,0.200000,2025-01-03 00:00:00,2025-01-01 00:00:00,2025-01-02 00:00:00,-4.000000,0.000000,1.000000
25%,2025-04-01 00:00:00,2.000000,860.260000,13.000000,2.000000,2025-04-06 00:00:00,2025-04-02 00:00:00,2025-04-07 00:00:00,0.000000,0.000000,2.800000
50%,2025-07-02 00:00:00,3.000000,1512.660000,20.200000,3.400000,2025-07-06 00:00:00,2025-07-02 00:00:00,2025-07-07 00:00:00,1.000000,0.000000,3.400000
75%,2025-09-30 00:00:00,4.000000,2982.252500,29.600000,5.280000,2025-10-05 00:00:00,2025-10-01 00:00:00,2025-10-06 00:00:00,2.000000,0.000000,4.100000
max,2025-12-31 00:00:00,5.000000,9447.990000,100.000000,25.850000,2026-01-07 00:00:00,2026-01-01 00:00:00,2026-01-10 00:00:00,6.000000,1.000000,5.000000
std,NaN,1.409296,1757.469899,12.997605,2.662416,NaN,NaN,NaN,1.457331,0.242057,0.893073

In [26]:
df.shape

(23698, 24)

In [27]:
df.isnull().sum()

order_id                  0
order_date                0
customer_id               0
customer_segment          0
customer_city             0
warehouse_id              0
warehouse_city            0
product_category          0
quantity                  0
order_value               0
delivery_partner          0
vehicle_type              0
shipping_mode             0
distance_km               0
package_weight_kg         0
promised_delivery_date    0
dispatch_date             0
delivery_date             0
delivery_status           0
delay_days                0
weather_condition         0
return_flag               0
return_reason             0
customer_rating           0
dtype: int64

In [28]:
df["customer_rating"].value_counts()

customer_rating
5.0    1286
3.0     988
3.5     979
3.4     966
3.2     951
3.3     934
3.1     927
2.9     905
3.6     886
3.8     874
2.8     869
3.7     836
2.7     811
4.0     806
3.9     801
2.6     736
4.2     716
4.1     706
2.5     693
4.3     655
4.4     609
2.4     583
4.5     560
2.3     545
4.6     523
2.2     470
4.7     461
4.8     415
2.1     406
4.9     351
2.0     312
1.9     272
1.8     218
1.7     166
1.6     135
1.5      99
1.4      69
1.0      67
1.3      52
1.1      33
1.2      27
Name: count, dtype: int64

In [29]:
df["customer_rating"].unique()

array([2.3, 3.1, 3.9, 4.1, 3. , 4.4, 3.7, 2.7, 1.8, 3.8, 2.8, 5. , 4.8,
       3.4, 2.5, 2.2, 4. , 4.2, 2.6, 3.5, 4.9, 4.5, 2.4, 1.3, 3.2, 2.9,
       1. , 3.3, 2. , 4.3, 1.9, 4.6, 3.6, 2.1, 4.7, 1.5, 1.4, 1.7, 1.6,
       1.2, 1.1])

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
(df["quantity"]<=0).sum()

np.int64(0)

In [32]:
(df["order_value"]<=0).sum()

np.int64(0)

In [33]:
(df["distance_km"]<=0).sum()

np.int64(0)

## 7. Export the Cleaned Dataset

Save the cleaned dataset as a CSV file for use in exploratory data analysis, SQL analysis, and visualization.

In [34]:
df.to_csv("../data/processed/delivery_operations_clean.csv",index=False)

PermissionError: [Errno 13] Permission denied: '../data/processed/delivery_operations_clean.csv'